name: Publish

on:
  push:
    branches:
      - saga

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SNOWPACK_PUBLIC_AUTH0_DOMAIN: distributeaid.eu.auth0.com
  SNOWPACK_PUBLIC_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}

jobs:
  main:
    runs-on: ubuntu-latest

    environment: github-pages

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Build
        run: npm run build
      - name: Publish latest release to GitHub pages
        run: |
          echo "machine github.com login authtoken password ${GITHUB_TOKEN}" > ~/.netrc
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          cd build
          touch .nojekyll
          git init
          git add -A
          git commit -m 'latest release'
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git push -f origin HEAD:gh-pages
